### PR TITLE
 C++17 type std::optional support

### LINKED ISSUE #326: Add support for C++17 type std::optional
It is desirable to support the following:

```cpp
using v_t = std::optional<std::string>;
nanodbc::result r = nanodbc::execute(connection, "SELECT a, b FROM t");
auto v0 = r.get<v_t>(0);
```

And, if `is_null(0) == true` then `v0.has_value() == false`.

The `std::optional` support would serve as an alternative to `result::get<T>(column, fallback)` syntax.

### PR DESCRIPTION
**Pull request by MichalPalkaMobica**
## What does this PR do?

This PR adds support for C++17 type std::optional ~with backward compatibility in C++14 via std::experimental::optional~ - @mloskot removed `std::experimental::optional` support as unnecessary.

## What are related issues/pull requests?

- Closes #326

## Tasklist

 - [x] Add test case(s)
 - [x] Review
 - [x] Adjust for comments
 - [x] All CI builds and checks have passed

### CODE REVIEW

**Comment by mloskot** [comment]
Are we certain about `std::experimental::optional` availability across all C++14 supporting clang and gcc?

**Comment by MichalPalkaMobica** [comment]
> Are we certain about `std::experimental::optional` availability across all C++14 supporting clang and gcc?

Of course not, my bad. I will fix it soon.

**Comment by mloskot** [comment]
I have just merged `main` to update to this PR to pick up recent changes to CI and `clang-format` runs.
I did not want to rebase to not to cause any trouble to your local repo.

**Comment by mloskot** [comment]
I've taken the liberty to update this PR and catch up with recent CI updates.

**Comment by mloskot** [comment]
Thanks @MichalPalkaMobica for your contribution

**Pull request merged**
