### PR TITLE
Add missing include

### PR DESCRIPTION
**Pull request by traceon**
## What does this PR do?
Fixes compilation under macOS using Homebrew's vanilla GCC.

### CODE REVIEW

**Comment by lexicalunit** [comment]
Thanks!!

**Review by mloskot — APPROVED** [review]
Thanks

**Comment by traceon** [comment]
Is `continuous-integration/travis-ci` check frozen or something?

**Comment by mloskot** [comment]
@traceon Travis CI R.I.P. 
We're migrating to GitHub Actions, but it's taking (too) long time, sorry :(

**Pull request merged**
