### PR TITLE
Feature/block fetch scrollable support

### PR DESCRIPTION
**Pull request by detule**
Hello:

This is an attempt to close out [this long-standing PR.](https://github.com/nanodbc/nanodbc/pull/229)

* Prior to this PR using "block" cursors to fetch multiple rows at a time works as expected as long as there are no "long" columns in the result.
* With https://github.com/nanodbc/nanodbc/pull/229 @wakusei suggested using `SQLSetPos` to move within the rowset to retrieve "long" columns.
* To complete his work I made the following additional changes:
  * Need to be careful about intermixing `SQL_ATTR_PARAMSET_SIZE` ( size of arrays that are bound to parameters ) and `SQL_ATTR_ROW_ARRAY_SIZE` ( size of rowset ).  With the ODBC Driver 17 for SQL Server, calling `SQLSetPos` with PARAMSET_SIZE set to a value > 1 leads to "invalid cursor position" error. Introduce `batch_ops` struct that allows for separation, and a version of `statement::just_execute` that uses this argument.  May need to expand to other methods as needed.
  * Hopefully all modern-day drivers support scrollable cursors, as they are necessary to be able to set the position of the cursor within the rowset.  However, some may not ( already seeing some indication that the `snowflake` OEM driver has shakey support.  It does not support `SQLSetPos` for example ).  Therefore setting the cursor to be scrollable ( necessary for block retrieval of data that contains LONG fields ) has to be optional. Somewhat inconveniently the cursor type needs to be specified before the statement is executed - otherwise we could set the type only if we could suss out if there was long data in the result.  Deal with these pre-execution attributes similarly to how we dealt with pre-connect connection attributes - in particular pull out `connection::attribute` to `nanodbc::attribute`.  Both `connection` and `statement` specialize by  adding a friend to their attribute type.

  NOTE: When we introduced `connection::attribute` we did it using `std::variant`.  As a result, the ability to set statement attributes ( and therefore, use block cursors in a way that is robust to long data in the result ) is limited to C++17 or better.

Feedback welcome!

### CODE REVIEW

**Review by mloskot — CHANGES_REQUESTED** [review]
@detule Thanks a lot for picking up @Wakusei 's work

This generally looks good to me, but would it be possible to review and address at least some of the static analysis warnings reported by the  `Code scanning / PREfast`?

**Comment by detule** [comment]
> @detule Thanks a lot for picking up @Wakusei 's work
> 
> This generally looks good to me, but would it be possible to review and address at least some of the static analysis warnings reported by the `Code scanning / PREfast`?

Thanks!
I gave the static analysis notes a go.  Let me know if I missed anything or if you have other suggestions.

**Review by mloskot — APPROVED** [review]
Thank you @detule 

Let's give @lexicalunit some time to have a look at this PR.

**Comment by lexicalunit** [comment]
> Let's give @lexicalunit some time to have a look at this PR.

Looks good!

**Review by lexicalunit — APPROVED** [review]

**Comment by detule** [comment]
Thanks all!

I think we can probably go ahead and close https://github.com/nanodbc/nanodbc/pull/229

Thanks again

**Comment by mloskot** [comment]
@detule  Good catch, done

**Pull request merged**
