### PR TITLE
Added support for binding std::string_view in statement.bind_strings()

### PR DESCRIPTION
**Pull request by emruiz81**
## What does this PR do?
It adds support for calling bind_strings() with std::string_view or std::wstring_view (and other c++ unicode implementations) values.

## What are related issues/pull requests?
No issues at all. But I've found that I had to construct new std::string objects and then insert them into a std::vector when calling statement::bind_strings(). This adds some overhead to my code, and using string_view objects prevents making an extra copy of every parameter.

What bind_strings() does if calling it with a vector of strings, is to construct a new buffer from it. But it just iterate the string values calling begin()/end() methods, no c_str() or data() is used there. Therefore, string_view objects are 100% compatible with that implementation.

### CODE REVIEW

**Review by mloskot — CHANGES_REQUESTED** [review]
Thanks for the contribution, but it needs a n update. The README.md says:
> New contributions submitted via Pull Requests must include corresponding tests.

**Comment by emruiz81** [comment]
> Thanks for the contribution, but it needs a n update. The README.md says:
> 
> > New contributions submitted via Pull Requests must include corresponding tests.

Thanks for your feedback. I've just added a new test based on test_string_vector but using string_view parameters. It is enabled only for C++17 compilers and above

**Review by mloskot — APPROVED** [review]
LGTM

Thanks!

**Comment by lexicalunit** [comment]
Very cool!

**Comment by mloskot** [comment]
Everyone, I opened https://github.com/nanodbc/nanodbc/discussions/321 with discussion related to C++ standard version.

**Pull request merged**
